/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exercises_list"];
        put?: never;
        post: operations["exercises_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exercises_retrieve"];
        put: operations["exercises_update"];
        post?: never;
        delete: operations["exercises_destroy"];
        options?: never;
        head?: never;
        patch: operations["exercises_partial_update"];
        trace?: never;
    };
    "/api/exercises/filters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exercises_filters_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Delete refresh token cookie */
        post: operations["logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/privacy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["privacy_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["programs_list"];
        put?: never;
        post: operations["programs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["programs_retrieve"];
        put: operations["programs_update"];
        post?: never;
        delete: operations["programs_destroy"];
        options?: never;
        head?: never;
        patch: operations["programs_partial_update"];
        trace?: never;
    };
    "/api/programs/filters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["programs_filters_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/request-password-reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["request_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reset-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-programs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Only:
         *     - GET /user-programs/
         *     - POST /user-programs/
         *     - GET /user-programs/{id}/
         *     - PATCH /user-programs/{id}/
         */
        get: operations["user_programs_list"];
        put?: never;
        /**
         * @description Only:
         *     - GET /user-programs/
         *     - POST /user-programs/
         *     - GET /user-programs/{id}/
         *     - PATCH /user-programs/{id}/
         */
        post: operations["user_programs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-programs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Only:
         *     - GET /user-programs/
         *     - POST /user-programs/
         *     - GET /user-programs/{id}/
         *     - PATCH /user-programs/{id}/
         */
        get: operations["user_programs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Only:
         *     - GET /user-programs/
         *     - POST /user-programs/
         *     - GET /user-programs/{id}/
         *     - PATCH /user-programs/{id}/
         */
        patch: operations["user_programs_partial_update"];
        trace?: never;
    };
    "/api/user-programs/{user_program_id}/feedbacks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Only:
         *     - GET /user-programs/{id}/feedback/
         *     - POST /user-programs/{id}/feedback/
         *     - GET /user-programs/{id}/feedback/{id}/
         */
        get: operations["user_programs_feedbacks_list"];
        put?: never;
        /**
         * @description Only:
         *     - GET /user-programs/{id}/feedback/
         *     - POST /user-programs/{id}/feedback/
         *     - GET /user-programs/{id}/feedback/{id}/
         */
        post: operations["user_programs_feedbacks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-programs/{user_program_id}/feedbacks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Only:
         *     - GET /user-programs/{id}/feedback/
         *     - POST /user-programs/{id}/feedback/
         *     - GET /user-programs/{id}/feedback/{id}/
         */
        get: operations["user_programs_feedbacks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-programs/{user_program_id}/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Only:
         *     - GET /user-programs/{id}/sessions/
         *     - POST /user-programs/{id}/sessions/
         *     - GET /user-programs/{user_program_id}/sessions/{id}/
         *     - DELETE /user-programs/{user_program_id}/sessions/{id}/
         */
        get: operations["user_programs_sessions_list"];
        put?: never;
        /**
         * @description Only:
         *     - GET /user-programs/{id}/sessions/
         *     - POST /user-programs/{id}/sessions/
         *     - GET /user-programs/{user_program_id}/sessions/{id}/
         *     - DELETE /user-programs/{user_program_id}/sessions/{id}/
         */
        post: operations["user_programs_sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-programs/{user_program_id}/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Only:
         *     - GET /user-programs/{id}/sessions/
         *     - POST /user-programs/{id}/sessions/
         *     - GET /user-programs/{user_program_id}/sessions/{id}/
         *     - DELETE /user-programs/{user_program_id}/sessions/{id}/
         */
        get: operations["user_programs_sessions_retrieve"];
        put?: never;
        post?: never;
        /**
         * @description Only:
         *     - GET /user-programs/{id}/sessions/
         *     - POST /user-programs/{id}/sessions/
         *     - GET /user-programs/{user_program_id}/sessions/{id}/
         *     - DELETE /user-programs/{user_program_id}/sessions/{id}/
         */
        delete: operations["user_programs_sessions_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-programs/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /user-programs/active/
         *     Return active instance for current user, or null if none.
         */
        get: operations["user_programs_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user_stats_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new user (public) */
        post: operations["users_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the current authenticated user */
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        /** @description Retrieve the current authenticated user */
        delete: operations["users_me_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        ChangePassword: {
            old_password: string;
            new_password: string;
        };
        ChangePasswordError: {
            detail: string;
        };
        ChangePasswordResponse: {
            message: string;
        };
        Cycle: {
            cycle: number;
            sessions: components["schemas"]["Session"][];
        };
        Exercise: {
            /** @description Slugified version of the English name, auto-generated */
            readonly slug: string;
            /** @description Translated field (django-parler) */
            name: string;
            /** @description Translated field (django-parler) */
            description: string;
            /**
             * @description Does this exercise count by repetitions or seconds?
             *
             *     * `repetition` - Repetition
             *     * `duration` - Duration
             */
            resolution?: components["schemas"]["ResolutionEnum"];
            practice_zone?: components["schemas"]["PracticeZoneEnum"];
            /** Format: uri */
            image?: string | null;
            /** Format: uri */
            gif?: string | null;
            /** Format: uri */
            video?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ExerciseFilters: {
            resolution: components["schemas"]["ResolutionFilter"][];
            practice_zone: components["schemas"]["PracticeZoneFilter"][];
        };
        ExercisePreview: {
            slug: string;
            name: string;
            description: string;
            resolution: string;
            practice_zone: string;
            value: number;
        };
        FocusAxesFilter: {
            value: components["schemas"]["FocusAxisEnum"];
            label: string;
        };
        /**
         * @description * `technical_bouldering` - Technical bouldering
         *     * `project_bouldering` - Project bouldering
         *     * `route_technique` - Route technique
         *     * `movement_quality` - Movement quality
         *     * `coordination` - Coordination
         *     * `footwork` - Footwork
         *     * `power` - Power
         *     * `max_strength` - Max strength
         *     * `power_endurance` - Power endurance
         *     * `endurance_continuity` - Endurance / continuity
         *     * `climbing_volume` - Climbing volume
         *     * `finger_strength` - Finger strength
         *     * `upper_body_strength` - Upper body strength
         *     * `core_tension` - Core tension
         *     * `lock_off_strength` - Lock-off strength
         *     * `pulling_strength` - Pulling strength
         *     * `general_strength` - General strength
         *     * `mobility` - Mobility
         *     * `stability` - Stability
         *     * `balance` - Balance
         *     * `conditioning` - Conditioning
         *     * `active_recovery` - Active recovery
         *     * `injury_prevention` - Injury prevention
         *     * `antagonist_training` - Antagonist training
         *     * `progressive_overload` - Progressive overload
         *     * `deload` - Deload / recovery
         *     * `movement_efficiency` - Movement efficiency
         * @enum {string}
         */
        FocusAxisEnum: "technical_bouldering" | "project_bouldering" | "route_technique" | "movement_quality" | "coordination" | "footwork" | "power" | "max_strength" | "power_endurance" | "endurance_continuity" | "climbing_volume" | "finger_strength" | "upper_body_strength" | "core_tension" | "lock_off_strength" | "pulling_strength" | "general_strength" | "mobility" | "stability" | "balance" | "conditioning" | "active_recovery" | "injury_prevention" | "antagonist_training" | "progressive_overload" | "deload" | "movement_efficiency";
        /**
         * @description * `general_fitness` - General fitness
         *     * `climbing_performance` - Climbing performance
         * @enum {string}
         */
        FocusEnum: "general_fitness" | "climbing_performance";
        FocusFilter: {
            value: components["schemas"]["FocusEnum"];
            label: string;
        };
        /**
         * @description * `beginner` - Beginner
         *     * `intermediate` - Intermediate
         *     * `advanced` - Advanced
         * @enum {string}
         */
        LevelEnum: "beginner" | "intermediate" | "advanced";
        LevelFilter: {
            value: components["schemas"]["LevelEnum"];
            label: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PasswordReset: {
            /** Format: uuid */
            token: string;
            new_password: string;
        };
        PasswordResetErrorResponse: {
            detail: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetRequestResponse: {
            message: string;
        };
        PasswordResetResponse: {
            message: string;
        };
        PatchedExercise: {
            /** @description Slugified version of the English name, auto-generated */
            readonly slug?: string;
            /** @description Translated field (django-parler) */
            name?: string;
            /** @description Translated field (django-parler) */
            description?: string;
            /**
             * @description Does this exercise count by repetitions or seconds?
             *
             *     * `repetition` - Repetition
             *     * `duration` - Duration
             */
            resolution?: components["schemas"]["ResolutionEnum"];
            practice_zone?: components["schemas"]["PracticeZoneEnum"];
            /** Format: uri */
            image?: string | null;
            /** Format: uri */
            gif?: string | null;
            /** Format: uri */
            video?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedProgram: {
            /** Format: uuid */
            readonly id?: string;
            /** @description Slugified version of the English name, auto-generated */
            readonly slug?: string;
            /** @description Translated field (django-parler) */
            name?: string;
            /** @description Translated field (django-parler) */
            description?: string;
            realistic_if?: string[];
            not_realistic_if?: string[];
            focus?: components["schemas"]["FocusEnum"];
            level?: components["schemas"]["LevelEnum"];
            /** @description Duration of program in days */
            duration_days?: number;
            is_public?: boolean;
            content?: unknown;
            focus_axes?: components["schemas"]["FocusAxisEnum"][];
            cycle_rhythm?: unknown;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedUserProgram: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly user?: string;
            /** Format: uuid */
            program?: string;
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly next_cycle?: number;
            readonly next_session_in_cycle?: number;
            readonly program_name?: string;
            /** Format: date-time */
            readonly start_date?: string;
            /** Format: date-time */
            readonly end_date?: string;
            readonly status_display?: string;
        };
        /**
         * @description * `everywhere` - Everywhere
         *     * `climbing_gym` - Climbing Gym
         * @enum {string}
         */
        PracticeZoneEnum: "everywhere" | "climbing_gym";
        PracticeZoneFilter: {
            value: components["schemas"]["PracticeZoneEnum"];
            label: string;
        };
        PrivacyPolicy: {
            /** @description Translated field (django-parler) */
            short_text: string;
            /** @description Translated field (django-parler) */
            long_text: string;
        };
        Program: {
            /** Format: uuid */
            readonly id: string;
            /** @description Slugified version of the English name, auto-generated */
            readonly slug: string;
            /** @description Translated field (django-parler) */
            name: string;
            /** @description Translated field (django-parler) */
            description: string;
            realistic_if?: string[];
            not_realistic_if?: string[];
            focus?: components["schemas"]["FocusEnum"];
            level?: components["schemas"]["LevelEnum"];
            /** @description Duration of program in days */
            duration_days?: number;
            is_public?: boolean;
            content?: unknown;
            focus_axes?: components["schemas"]["FocusAxisEnum"][];
            cycle_rhythm?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ProgramDetail: {
            /** Format: uuid */
            readonly id: string;
            /** @description Translated field (django-parler) */
            name: string;
            /** @description Translated field (django-parler) */
            description: string;
            realistic_if?: string[];
            not_realistic_if?: string[];
            focus?: components["schemas"]["FocusEnum"];
            level?: components["schemas"]["LevelEnum"];
            /** @description Duration of program in days */
            duration_days?: number;
            focus_axes?: components["schemas"]["FocusAxisEnum"][];
            readonly content: components["schemas"]["ProgramDetailContent"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ProgramDetailContent: {
            cycles: components["schemas"]["Cycle"][];
            total_cycles: number;
            sessions_per_cycles: number;
            total_sessions: number;
        };
        ProgramFilters: {
            level: components["schemas"]["LevelFilter"][];
            focus: components["schemas"]["FocusFilter"][];
            focus_axes: components["schemas"]["FocusAxesFilter"][];
        };
        ProgramList: {
            /** Format: uuid */
            readonly id: string;
            /** @description Translated field (django-parler) */
            name: string;
            /** @description Translated field (django-parler) */
            description: string;
            level?: components["schemas"]["LevelEnum"];
            focus?: components["schemas"]["FocusEnum"];
            /** @description Duration of program in days */
            duration_days?: number;
        };
        /**
         * @description * `too_easy` - Too Easy
         *     * `ok` - OK
         *     * `too_hard` - Too Hard
         * @enum {string}
         */
        RatingEnum: "too_easy" | "ok" | "too_hard";
        /**
         * @description * `repetition` - Repetition
         *     * `duration` - Duration
         * @enum {string}
         */
        ResolutionEnum: "repetition" | "duration";
        ResolutionFilter: {
            value: components["schemas"]["ResolutionEnum"];
            label: string;
        };
        Session: {
            session: number;
            sequences: components["schemas"]["ExercisePreview"][][];
        };
        /**
         * @description * `active` - Active
         *     * `completed` - Completed
         *     * `abandoned` - Abandoned
         * @enum {string}
         */
        StatusEnum: "active" | "completed" | "abandoned";
        TokenObtainPair: {
            email: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenResponse: {
            access: string;
            refresh?: string;
        };
        /**
         * @description * `not_useful` - Not Useful
         *     * `useful` - Useful
         *     * `very_useful` - Very Useful
         * @enum {string}
         */
        UsefulnessEnum: "not_useful" | "useful" | "very_useful";
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            is_active?: boolean;
            readonly is_staff: boolean;
            /** Format: date-time */
            readonly date_joined: string;
        };
        UserCreate: {
            /** Format: email */
            email: string;
            first_name?: string;
            last_name?: string;
            password: string;
            gdpr_consent?: boolean;
        };
        UserProgram: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly user: string;
            /** Format: uuid */
            program: string;
            status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly next_cycle: number;
            readonly next_session_in_cycle: number;
            readonly program_name: string;
            /** Format: date-time */
            readonly start_date: string;
            /** Format: date-time */
            readonly end_date: string;
            readonly status_display: string;
        };
        UserProgramFeedback: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly user_program: string;
            usefulness?: (components["schemas"]["UsefulnessEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            would_repeat?: boolean;
            comment?: string;
        };
        UserProgramSession: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly user_program: string;
            session_in_cycle: number;
            cycle_count: number;
            readonly completed: boolean;
            session_snapshot: unknown;
            rating?: (components["schemas"]["RatingEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        UserStats: {
            total_sessions_completed: number;
            total_programs_completed: number;
            current_level: (components["schemas"]["LevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            highest_level_completed: (components["schemas"]["LevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePassword"];
                "multipart/form-data": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordError"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordError"];
                };
            };
        };
    };
    exercises_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
        };
    };
    exercises_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exercise"];
                "application/x-www-form-urlencoded": components["schemas"]["Exercise"];
                "multipart/form-data": components["schemas"]["Exercise"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    exercises_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this exercise. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    exercises_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this exercise. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Exercise"];
                "application/x-www-form-urlencoded": components["schemas"]["Exercise"];
                "multipart/form-data": components["schemas"]["Exercise"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    exercises_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this exercise. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exercises_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this exercise. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedExercise"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedExercise"];
                "multipart/form-data": components["schemas"]["PatchedExercise"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    exercises_filters_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseFilters"];
                };
            };
        };
    };
    logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail?: string;
                    };
                };
            };
        };
    };
    privacy_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacyPolicy"];
                };
            };
        };
    };
    programs_list: {
        parameters: {
            query?: {
                /**
                 * @description * `general_fitness` - General fitness
                 *     * `climbing_performance` - Climbing performance
                 */
                focus?: "climbing_performance" | "general_fitness";
                /**
                 * @description * `technical_bouldering` - Technical bouldering
                 *     * `project_bouldering` - Project bouldering
                 *     * `route_technique` - Route technique
                 *     * `movement_quality` - Movement quality
                 *     * `coordination` - Coordination
                 *     * `footwork` - Footwork
                 *     * `power` - Power
                 *     * `max_strength` - Max strength
                 *     * `power_endurance` - Power endurance
                 *     * `endurance_continuity` - Endurance / continuity
                 *     * `climbing_volume` - Climbing volume
                 *     * `finger_strength` - Finger strength
                 *     * `upper_body_strength` - Upper body strength
                 *     * `core_tension` - Core tension
                 *     * `lock_off_strength` - Lock-off strength
                 *     * `pulling_strength` - Pulling strength
                 *     * `general_strength` - General strength
                 *     * `mobility` - Mobility
                 *     * `stability` - Stability
                 *     * `balance` - Balance
                 *     * `conditioning` - Conditioning
                 *     * `active_recovery` - Active recovery
                 *     * `injury_prevention` - Injury prevention
                 *     * `antagonist_training` - Antagonist training
                 *     * `progressive_overload` - Progressive overload
                 *     * `deload` - Deload / recovery
                 *     * `movement_efficiency` - Movement efficiency
                 */
                focus_axes?: ("active_recovery" | "antagonist_training" | "balance" | "climbing_volume" | "conditioning" | "coordination" | "core_tension" | "deload" | "endurance_continuity" | "finger_strength" | "footwork" | "general_strength" | "injury_prevention" | "lock_off_strength" | "max_strength" | "mobility" | "movement_efficiency" | "movement_quality" | "power" | "power_endurance" | "progressive_overload" | "project_bouldering" | "pulling_strength" | "route_technique" | "stability" | "technical_bouldering" | "upper_body_strength")[];
                /**
                 * @description * `beginner` - Beginner
                 *     * `intermediate` - Intermediate
                 *     * `advanced` - Advanced
                 */
                level?: "advanced" | "beginner" | "intermediate";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramList"][];
                };
            };
        };
    };
    programs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Program"];
                "application/x-www-form-urlencoded": components["schemas"]["Program"];
                "multipart/form-data": components["schemas"]["Program"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
        };
    };
    programs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this program. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramDetail"];
                };
            };
        };
    };
    programs_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this program. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Program"];
                "application/x-www-form-urlencoded": components["schemas"]["Program"];
                "multipart/form-data": components["schemas"]["Program"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
        };
    };
    programs_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this program. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    programs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this program. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProgram"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProgram"];
                "multipart/form-data": components["schemas"]["PatchedProgram"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"];
                };
            };
        };
    };
    programs_filters_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramFilters"];
                };
            };
        };
    };
    request_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetRequestResponse"];
                };
            };
        };
    };
    reset_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordReset"];
                "multipart/form-data": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetErrorResponse"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "en" | "es" | "fr";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            /** @description JWT tokens + HttpOnly refresh_token cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    user_programs_list: {
        parameters: {
            query?: {
                program?: string;
                /**
                 * @description * `active` - Active
                 *     * `completed` - Completed
                 *     * `abandoned` - Abandoned
                 */
                status?: "abandoned" | "active" | "completed";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgram"][];
                };
            };
        };
    };
    user_programs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProgram"];
                "application/x-www-form-urlencoded": components["schemas"]["UserProgram"];
                "multipart/form-data": components["schemas"]["UserProgram"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgram"];
                };
            };
        };
    };
    user_programs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user program. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgram"];
                };
            };
        };
    };
    user_programs_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this user program. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserProgram"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserProgram"];
                "multipart/form-data": components["schemas"]["PatchedUserProgram"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgram"];
                };
            };
        };
    };
    user_programs_feedbacks_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgramFeedback"][];
                };
            };
        };
    };
    user_programs_feedbacks_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_program_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserProgramFeedback"];
                "application/x-www-form-urlencoded": components["schemas"]["UserProgramFeedback"];
                "multipart/form-data": components["schemas"]["UserProgramFeedback"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgramFeedback"];
                };
            };
        };
    };
    user_programs_feedbacks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                user_program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgramFeedback"];
                };
            };
        };
    };
    user_programs_sessions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgramSession"][];
                };
            };
        };
    };
    user_programs_sessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_program_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProgramSession"];
                "application/x-www-form-urlencoded": components["schemas"]["UserProgramSession"];
                "multipart/form-data": components["schemas"]["UserProgramSession"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgramSession"];
                };
            };
        };
    };
    user_programs_sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                user_program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgramSession"];
                };
            };
        };
    };
    user_programs_sessions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                user_program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_programs_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProgram"];
                };
            };
        };
    };
    user_stats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStats"];
                };
            };
        };
    };
    users_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCreate"];
                "multipart/form-data": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCreate"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
